### ISSUE TITLE
required with jquery validator 

### ISSUE THREAD

**Issue by yskraus** [s43/Simple-File-Input#1]
How can I set the required attribute without overwriting the ignore in validator?

**Comment by s43** [comment]
Can you show me an example of what you're trying to do, with a native file input ? ( fiddle or codepen )

**Comment by yskraus** [comment]
I wanna make the file field required 
I did it like this 
`      ignore: "input[type!='file']:hidden",
      rules: {
          file: {
              required: true,
          },
}
`
my question is if there is a way with the plugin to do it

**Comment by s43** [comment]
I got your point, for the moment there's no relating between sfi & jQuery validate, but the reason that makes the validator ignores your file input is that it's been hidden ( display:none ), force it to be block, and hide it with visibility & set it dimensions to zero, and it should work then.

I'll commit a change to the plugin very soon to solve this kind of conflicts.

**Comment by yskraus** [comment]
also a good idea tnx

**Comment by s43** [comment]
Glad it fixed your issue, I'll set this as resolved ;)

**Comment by yskraus** [comment]
also add cursor: pointer

**Comment by s43** [comment]
Where exactly ? Upload trigger is an a tag, which gives it a pointer cursor by default, don't you think so ? But if you something that represents an issue, I'd really appreciate your contribution :) big up

**Comment by yskraus** [comment]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/16155667/23774605/65a57018-04f2-11e7-81c7-3f24e6f73ba8.png)

**Comment by s43** [comment]
I don't think that this area needs a pointer cursor by default, it's to the user to set those additional properties depending on his needs

**Comment by yskraus** [comment]
Aha no problem

**Comment by s43** [comment]
Thanks for paying attention ; ), I do really appreciate that.
